apiVersion: apps/v1
kind: Deployment
metadata:
  name: nrf
  labels:
    app: nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nrf
  template:
    metadata:
      labels:
        app: nrf
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"{{ .Values.nrf.ipv4Addr }}\"]"
    spec:
      containers:
        - name: nrf
          image: ycchan5566/free5gc:v3.0.6
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args: ["-c", "./bin/nrf"]
          stdin: true
          tty: true
          volumeMounts:
            - name: free5gc-config
              mountPath: /root/free5gc/config/free5GC.conf
              subPath: free5GC.conf
            - name: nrf-config
              mountPath: /root/free5gc/config/nrfcfg.yaml
              subPath: nrfcfg.yaml
      #nodeSelector: 
      #  type: core
      volumes:
        - name: free5gc-config
          configMap:
            name: free5gc
        - name: nrf-config
          configMap:
            name: nrf
