apiVersion: v1
kind: ConfigMap
metadata:
  name: uerouting
data:
  uerouting.yaml: |
    info:
      version: 1.0.1
      description: Routing information for UE

    ueRoutingInfo: # the list of UE routing information
      UE1: # Group Name
        members:
        - imsi-208930000000003 # Subscription Permanent Identifier of the UE
        - imsi-208930000000004 # Subscription Permanent Identifier of the UE
        topology: 
        # Network topology for this group (Uplink: A->B, Downlink: B->A)
        # default path derived from this topology
        # node name should be consistent with smfcfg.yaml
          - A: gNB1
            B: ULCL
          - A: ULCL
            B: UPF1
        specificPath:
          - dest: 10.10.3.0/24 # the destination IP address on Data Network (DN)
            # the order of UPF nodes in this path. We use the UPF's name to represent each UPF node.
            # The UPF's name should be consistent with smfcfg.yaml
            path: [ULCL, ULCL]
          #- dest: 140.113.194.233/32 # the destination IP address on Data Network (DN)
            # the order of UPF nodes in this path. We use the UPF's name to represent each UPF node.
            # The UPF's name should be consistent with smfcfg.yaml
          #  path: [ULCL, ULCL]
