apiVersion: apps/v1
kind: Deployment
metadata:
  name: ausf
  labels:
    app: ausf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ausf
  template:
    metadata:
      labels:
        app: ausf
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"{{ .Values.ausf.bindingIPv4 }}\"]"
    spec:
      containers:
        - name: ausf
          image: ycchan5566/free5gc:v3.0.6
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args: ["-c", "./bin/ausf"]
          stdin: true
          tty: true
          volumeMounts:
            - name: free5gc-config
              mountPath: /root/free5gc/config/free5GC.conf
              subPath: free5GC.conf
            - name: ausf-config
              mountPath: /root/free5gc/config/ausfcfg.yaml
              subPath: ausfcfg.yaml
      #nodeSelector: 
      #  type: core
      volumes:
        - name: free5gc-config
          configMap:
            name: free5gc
        - name: ausf-config
          configMap:
            name: ausf
