apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcf
  labels:
    app: pcf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pcf
  template:
    metadata:
      labels:
        app: pcf
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"{{ .Values.pcf.bindingIPv4 }}\"]"
    spec:
      containers:
        - name: pcf
          image: ycchan5566/free5gc:v3.0.6
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args: ["-c", "./bin/pcf"]
          stdin: true
          tty: true
          volumeMounts:
            - name: free5gc-config
              mountPath: /root/free5gc/config/free5GC.conf
              subPath: free5GC.conf
            - name: pcf-config
              mountPath: /root/free5gc/config/pcfcfg.yaml
              subPath: pcfcfg.yaml
      #nodeSelector: 
      #  type: core
      volumes:
        - name: free5gc-config
          configMap:
            name: free5gc
        - name: pcf-config
          configMap:
            name: pcf
