apiVersion: apps/v1
kind: Deployment
metadata:
  name: amf
  labels:
    app: amf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amf
  template:
    metadata:
      labels:
        app: amf
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"{{ .Values.amf.bindingIPv4 }}\"]"
    spec:
      containers:
        - name: amf
          securityContext:
            privileged: true
          image: ycchan5566/free5gc:v3.0.6
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          # args: ["-c", "ethtool -K net1 tx off && ./bin/amf"]
          args: ["-c", "./bin/amf"]
          volumeMounts:
            - name: free5gc-config
              mountPath: /root/free5gc/config/free5GC.conf
              subPath: free5GC.conf
            - name: amf-config
              mountPath: /root/free5gc/config/amfcfg.yaml
              subPath: amfcfg.yaml
      #nodeSelector: 
      #  type: core
      volumes:
        - name: free5gc-config
          configMap:
            name: free5gc
        - name: amf-config
          configMap:
            name: amf
