apiVersion: v1
kind: Service
metadata:
  name: amf
  labels:
    app: amf
spec:
  type: NodePort
  selector:
    app: amf
  ports:
    - name: ngap
      protocol: SCTP
      port: 38412
      nodePort: 30412
