apiVersion: apps/v1
kind: Deployment
metadata:
  name: nssf
  labels:
    app: nssf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nssf
  template:
    metadata:
      labels:
        app: nssf
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"{{ .Values.nssf.bindingIPv4 }}\"]"
    spec:
      containers:
        - name: nssf
          image: ycchan5566/free5gc:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args: ["-c", "./bin/nssf"]
          stdin: true
          tty: true
          volumeMounts:
            - name: free5gc-config
              mountPath: /root/free5gc/config/free5GC.conf
              subPath: free5GC.conf
            - name: nssf-config
              mountPath: /root/free5gc/config/nssfcfg.yaml
              subPath: nssfcfg.yaml
      #nodeSelector: 
      #  type: core
      volumes:
        - name: free5gc-config
          configMap:
            name: free5gc
        - name: nssf-config
          configMap:
            name: nssf
