apiVersion: apps/v1
kind: Deployment
metadata:
  name: udm
  labels:
    app: udm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udm
  template:
    metadata:
      labels:
        app: udm
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"{{ .Values.udm.bindingIPv4 }}\"]"
    spec:
      containers:
        - name: udm
          image: ycchan5566/free5gc:v3.0.6
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args: ["-c", "./bin/udm"]
          stdin: true
          tty: true
          volumeMounts:
            - name: free5gc-config
              mountPath: /root/free5gc/config/free5GC.conf
              subPath: free5GC.conf
            - name: udm-config
              mountPath: /root/free5gc/config/udmcfg.yaml
              subPath: udmcfg.yaml
      #nodeSelector: 
      #  type: core
      volumes:
        - name: free5gc-config
          configMap:
            name: free5gc
        - name: udm-config
          configMap:
            name: udm
